services:
  - type: web
    name: mern-chat-app
    env: node
    plan: free
    buildCommand: |
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "mongodb+srv://singhans334:A8bLtDjHqOmWZDh7@cluster0.zqrdfyn.mongodb.net/chat-app-db?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "4G6nqQAJwtFNandFgDJeEZraiFD41chu2ej/kOKTrKc="
      - key: NODE_ENV
        value: "development"
